#!/usr/bin/env bash

# ------------------------ Begin license text for file -------------------------
#
# The MIT License (MIT)
#
# Copyright (c) 2021 Alexander Ross (alex@aross.se)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# ------------------------- End license text for file --------------------------
#
# Dependencies:
# - NeoVim Remote (https://github.com/mhinz/neovim-remote)
#
# Add the script below to your .vimrc file and restart all neovim sessions to
# make vim start using the correct colorscheme and allow it to switch when your
# macOS does.
#
#     function! DarkMode()
#       set background=dark
#       " Or whatever is needed to toggle preferred dark mode for you
#     endfunction
#
#     function! LightMode()
#       set background=light
#       " Or whatever is needed to toggle preferred light mode for you
#     endfunction
#
#     if (filereadable(expand("~/.config/appearance/current")) && readfile(expand("~/.config/appearance/current"))[0] == "Light")
#       call LightMode()
#     else
#       call DarkMode()
#     endif


set -exuo pipefail

NEOVIM_REMOTE="/usr/local/bin/nvr"

if ! command -v $NEOVIM_REMOTE &> /dev/null
then
  echo "Command \"nvr\" could not be found"
  echo "Install using: \"pip3 install neovim-remote\" or read more at https://github.com/mhinz/neovim-remote"
  exit 1
fi

for server in $($NEOVIM_REMOTE --serverlist)
do
  if [ "$1" == "Dark" ]; then
    $NEOVIM_REMOTE --servername $server -cc ":call DarkMode()"
  else
    $NEOVIM_REMOTE --servername $server -cc ":call LightMode()"
  fi
done
